<html>
	<head>
		


	</head>
	<body>



	<?php

		include_once 'classes.php';
		$database = new Database;
		$database -> connect();

		// student id needs to be posted from the login page
		//or something!
		//$student_id = $_GET['student_id'];

		$student_id = 1; //remove this eventually and replace it with
						//the get generated by the login page


		$database->read_student($student_id);

		$contact_details = $database->array_query;

			echo "</br></br></br>";

		//var_dump($database->read_student($student_id));

		echo "</br></br></br>";

		var_dump($contact_details);

	echo "</br></br></br>";


	?>

		<div id ="contact_details">
			Student ID: <?php echo $contact_details["student_id"] ?></br></br>
			First Name: <?php echo $contact_details["first_name"] ?></br></br>
			Last Name:	<?php echo $contact_details["last_name"] ?></br></br>
			Address: 	<?php echo $contact_details["address"] ?></br></br>
			e-mail: 	<?php echo $contact_details["email"] ?></br></br>
			phone:		<?php echo $contact_details["phone"] ?></br></br>
		</div>

		<div id ="upload_image">

			<form action="login.php" method="post">
				<!-- sort out folder permissions-->
			</form>

		</div>
		<?php 
			$first_name = $contact_details["first_name"];
			$last_name = $contact_details["last_name"];

		?>

		<div id ="buttons">
			<!-- call button and delete buttons / links will go here-->
				<?php echo "<a href='delete.php?first_name={$first_name}&last_name={$last_name}'>Delete Student</a>" ?>
			<!-- a link that goes to the delete page conting the id variable-->
		</div>

		<div id = "add_note">
			<form action = "profile.php" method="post">
				<input type="text" name = "add_note">
			</form>

		</div>

		<div id="validation_message">
			<!-- does this need to be initiated after the php has been triggered doe?-->
			
			<?php echo $validation_message ?>
			
		</div>

	</body>




</html>




<?php



?>